package genjson

const generatedFileTemplate = `// Code generated by genjson. DO NOT EDIT.
package {{ .PackageName }}
import (
"fmt"
"strconv"
genjsonrt "github.com/P4elme6ka/gen-json/pkg/genjson/runtime"
{{- if .UsesUUID }}
"github.com/google/uuid"
{{- end }}
)
{{- range .Types }}
{{- $type := . }}
func Decode{{ .Name }}(data []byte) ({{ .Name }}, error) {
	var out {{ .Name }}
{{- range .RequiredFields }}
	seen{{ .GoName }} := false
{{- end }}

	err := genjsonrt.DecodeObject(data, func(key []byte, value []byte) error {
		switch {
{{- range .Fields }}
		case genjsonrt.KeyEq(key, {{ printf "%q" .JSONName }}):
{{- if .Required }}
			seen{{ .GoName }} = true
{{- end }}
			{{- if eq .DecodeKind "string" }}
			parsed, err := genjsonrt.DecodeString(value)
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = parsed
			{{- else if eq .DecodeKind "ptr_string" }}
			if genjsonrt.IsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				parsed, err := genjsonrt.DecodeString(value)
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				out.{{ .GoName }} = &parsed
			}
			{{- else if eq .DecodeKind "bool" }}
			parsed, err := genjsonrt.DecodeBool(value)
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = parsed
			{{- else if eq .DecodeKind "ptr_bool" }}
			if genjsonrt.IsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				parsed, err := genjsonrt.DecodeBool(value)
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				out.{{ .GoName }} = &parsed
			}
			{{- else if or (eq .DecodeKind "int") (eq .DecodeKind "int8") (eq .DecodeKind "int16") (eq .DecodeKind "int32") (eq .DecodeKind "int64") (eq .DecodeKind "rune") }}
			parsed, err := genjsonrt.DecodeInt(value, {{- if or (eq .DecodeKind "int") -}} 0 {{- else if or (eq .DecodeKind "int8") -}} 8 {{- else if or (eq .DecodeKind "int16") -}} 16 {{- else if or (eq .DecodeKind "int32") (eq .DecodeKind "rune") -}} 32 {{- else -}} 64 {{- end -}})
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = {{ .BaseType }}(parsed)
			{{- else if or (eq .DecodeKind "ptr_int") (eq .DecodeKind "ptr_int8") (eq .DecodeKind "ptr_int16") (eq .DecodeKind "ptr_int32") (eq .DecodeKind "ptr_int64") (eq .DecodeKind "ptr_rune") }}
			if genjsonrt.IsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				parsed, err := genjsonrt.DecodeInt(value, {{- if or (eq .DecodeKind "ptr_int") -}} 0 {{- else if or (eq .DecodeKind "ptr_int8") -}} 8 {{- else if or (eq .DecodeKind "ptr_int16") -}} 16 {{- else if or (eq .DecodeKind "ptr_int32") (eq .DecodeKind "ptr_rune") -}} 32 {{- else -}} 64 {{- end -}})
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				tmp := {{ .BaseType }}(parsed)
				out.{{ .GoName }} = &tmp
			}
			{{- else if or (eq .DecodeKind "uint") (eq .DecodeKind "uint8") (eq .DecodeKind "uint16") (eq .DecodeKind "uint32") (eq .DecodeKind "uint64") (eq .DecodeKind "byte") }}
			parsed, err := genjsonrt.DecodeUint(value, {{- if eq .DecodeKind "uint" -}} 0 {{- else if or (eq .DecodeKind "uint8") (eq .DecodeKind "byte") -}} 8 {{- else if eq .DecodeKind "uint16" -}} 16 {{- else if eq .DecodeKind "uint32" -}} 32 {{- else -}} 64 {{- end -}})
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = {{ .BaseType }}(parsed)
			{{- else if or (eq .DecodeKind "ptr_uint") (eq .DecodeKind "ptr_uint8") (eq .DecodeKind "ptr_uint16") (eq .DecodeKind "ptr_uint32") (eq .DecodeKind "ptr_uint64") (eq .DecodeKind "ptr_byte") }}
			if genjsonrt.IsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				parsed, err := genjsonrt.DecodeUint(value, {{- if eq .DecodeKind "ptr_uint" -}} 0 {{- else if or (eq .DecodeKind "ptr_uint8") (eq .DecodeKind "ptr_byte") -}} 8 {{- else if eq .DecodeKind "ptr_uint16" -}} 16 {{- else if eq .DecodeKind "ptr_uint32" -}} 32 {{- else -}} 64 {{- end -}})
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				tmp := {{ .BaseType }}(parsed)
				out.{{ .GoName }} = &tmp
			}
			{{- else if or (eq .DecodeKind "float32") (eq .DecodeKind "float64") }}
			parsed, err := genjsonrt.DecodeFloat(value, {{- if eq .DecodeKind "float32" -}} 32 {{- else -}} 64 {{- end -}})
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = {{ .BaseType }}(parsed)
			{{- else if or (eq .DecodeKind "ptr_float32") (eq .DecodeKind "ptr_float64") }}
			if genjsonrt.IsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				parsed, err := genjsonrt.DecodeFloat(value, {{- if eq .DecodeKind "ptr_float32" -}} 32 {{- else -}} 64 {{- end -}})
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				tmp := {{ .BaseType }}(parsed)
				out.{{ .GoName }} = &tmp
			}
			{{- else if eq .DecodeKind "uuid" }}
			text, err := genjsonrt.DecodeText(value)
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			if u, ok := any(&out.{{ .GoName }}).(genjsonrt.TextUnmarshaler); ok {
				if err := u.UnmarshalText(text); err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
			} else {
				return genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $type.Name }}, Field: {{ printf "%q" .GoName }}, Op: "decode"}
			}
			{{- else if eq .DecodeKind "ptr_uuid" }}
			if genjsonrt.IsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				text, err := genjsonrt.DecodeText(value)
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				tmp := new({{ .BaseType }})
				if u, ok := any(tmp).(genjsonrt.TextUnmarshaler); ok {
					if err := u.UnmarshalText(text); err != nil {
						return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
					}
					out.{{ .GoName }} = tmp
				} else {
					return genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $type.Name }}, Field: {{ printf "%q" .GoName }}, Op: "decode"}
				}
			}
			{{- else if eq .DecodeKind "struct" }}
			parsed, err := Decode{{ .BaseType }}(value)
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = parsed
			{{- else if eq .DecodeKind "ptr_struct" }}
			if genjsonrt.IsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				parsed, err := Decode{{ .BaseType }}(value)
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				tmp := parsed
				out.{{ .GoName }} = &tmp
			}
			{{- else if eq .DecodeKind "slice" }}
			{{- if eq .ElemKind "slice" }}
			var arr [][]{{ .ElemType }}
			{{- else }}
			var arr []{{ .ElemType }}
			{{- end }}
			if err := genjsonrt.DecodeArray(value, func(elem []byte) error {
				{{- if eq .ElemKind "slice" }}
				var inner []{{ .ElemType }}
				if err := genjsonrt.DecodeArray(elem, func(innerElem []byte) error {
					vv, err := genjsonrt.DecodeInt(innerElem, 0)
					if err != nil {
						return err
					}
					inner = append(inner, {{ .ElemType }}(vv))
					return nil
				}); err != nil {
					return err
				}
				arr = append(arr, inner)
				return nil
				{{- end }}
				{{- if eq .ElemKind "string" }}
				v, err := genjsonrt.DecodeString(elem)
				if err != nil { return err }
				arr = append(arr, v)
				{{- else if eq .ElemKind "bool" }}
				v, err := genjsonrt.DecodeBool(elem)
				if err != nil { return err }
				arr = append(arr, v)
				{{- else if or (eq .ElemKind "int") (eq .ElemKind "int8") (eq .ElemKind "int16") (eq .ElemKind "int32") (eq .ElemKind "int64") (eq .ElemKind "rune") }}
				vv, err := genjsonrt.DecodeInt(elem, 0)
				if err != nil { return err }
				arr = append(arr, {{ .ElemType }}(vv))
				{{- else if or (eq .ElemKind "uint") (eq .ElemKind "uint8") (eq .ElemKind "uint16") (eq .ElemKind "uint32") (eq .ElemKind "uint64") (eq .ElemKind "byte") }}
				vv, err := genjsonrt.DecodeUint(elem, 0)
				if err != nil { return err }
				arr = append(arr, {{ .ElemType }}(vv))
				{{- else if or (eq .ElemKind "float32") (eq .ElemKind "float64") }}
				vv, err := genjsonrt.DecodeFloat(elem, 64)
				if err != nil { return err }
				arr = append(arr, {{ .ElemType }}(vv))
				{{- else if eq .ElemKind "uuid" }}
				txt, err := genjsonrt.DecodeText(elem)
				if err != nil { return err }
				var tmp {{ .ElemType }}
				if u, ok := any(&tmp).(genjsonrt.TextUnmarshaler); ok {
					if err := u.UnmarshalText(txt); err != nil { return err }
					arr = append(arr, tmp)
					return nil
				}
				return fmt.Errorf("unsupported slice elem")
				{{- else if eq .ElemKind "struct" }}
				vv, err := Decode{{ .ElemType }}(elem)
				if err != nil { return err }
				arr = append(arr, vv)
				{{- else }}
				return fmt.Errorf("unsupported slice elem")
				{{- end }}
				return nil
			}); err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = arr
			{{- else if eq .DecodeKind "map" }}
			m := make(map[string]{{ .ElemType }})
			if err := genjsonrt.DecodeMapObject(value, func(k string, elem []byte) error {
				{{- if eq .ElemKind "string" }}
				v, err := genjsonrt.DecodeString(elem)
				if err != nil { return err }
				m[k] = v
				{{- else if eq .ElemKind "bool" }}
				v, err := genjsonrt.DecodeBool(elem)
				if err != nil { return err }
				m[k] = v
				{{- else if or (eq .ElemKind "int") (eq .ElemKind "int8") (eq .ElemKind "int16") (eq .ElemKind "int32") (eq .ElemKind "int64") (eq .ElemKind "rune") }}
				vv, err := genjsonrt.DecodeInt(elem, 0)
				if err != nil { return err }
				m[k] = {{ .ElemType }}(vv)
				{{- else if or (eq .ElemKind "uint") (eq .ElemKind "uint8") (eq .ElemKind "uint16") (eq .ElemKind "uint32") (eq .ElemKind "uint64") (eq .ElemKind "byte") }}
				vv, err := genjsonrt.DecodeUint(elem, 0)
				if err != nil { return err }
				m[k] = {{ .ElemType }}(vv)
				{{- else if or (eq .ElemKind "float32") (eq .ElemKind "float64") }}
				vv, err := genjsonrt.DecodeFloat(elem, 64)
				if err != nil { return err }
				m[k] = {{ .ElemType }}(vv)
				{{- else if eq .ElemKind "uuid" }}
				txt, err := genjsonrt.DecodeText(elem)
				if err != nil { return err }
				var tmp {{ .ElemType }}
				if u, ok := any(&tmp).(genjsonrt.TextUnmarshaler); ok {
					if err := u.UnmarshalText(txt); err != nil { return err }
					m[k] = tmp
					return nil
				}
				return fmt.Errorf("unsupported map elem")
				{{- else if eq .ElemKind "struct" }}
				vv, err := Decode{{ .ElemType }}(elem)
				if err != nil { return err }
				m[k] = vv
				{{- else }}
				return fmt.Errorf("unsupported map elem")
				{{- end }}
				return nil
			}); err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = m
			{{- else }}
			if u, ok := any(&out.{{ .GoName }}).(genjsonrt.Unmarshaler); ok {
				if err := u.UnmarshalJSON(value); err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
			} else {
				return genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $type.Name }}, Field: {{ printf "%q" .GoName }}, Op: "decode"}
			}
			{{- end }}
{{- end }}
{{- if $.UnknownFields }}
		default:
			// Slow path: decode key string only for error message.
			k, err := strconv.Unquote(string(key))
			if err != nil {
				k = "<invalid key>"
			}
			return genjsonrt.UnknownFieldError{TypeName: {{ printf "%q" $type.Name }}, Field: k}
{{- end }}
		}
		return nil
	})
	if err != nil {
		return {{ .Name }}{}, err
	}

{{- if $.RequiredFieldsEnabled }}
{{- range .RequiredFields }}
	if !seen{{ .GoName }} {
		return {{ $type.Name }}{}, genjsonrt.MissingFieldError{TypeName: {{ printf "%q" $type.Name }}, Field: {{ printf "%q" .JSONName }}}
	}
{{- end }}
{{- end }}
	return out, nil
}

func Encode{{ .Name }}(v {{ .Name }}) ([]byte, error) {
	out := make([]byte, 0, 128)
	out = append(out, '{')
	wroteAny := false
{{- $typeName := .Name }}
	{{- range .Fields }}
	// Precomputed field token: {{ .JSONName }}
	var genjsonFieldTok{{ $typeName }}{{ .GoName }} = []byte({{ printf "%q" (printf "\"%s\":" .JSONName) }})
	{{- end }}
{{- range .Fields }}
{{- if .OmitEmpty }}
	if !genjsonrt.IsZero(v.{{ .GoName }}) {
		out = genjsonrt.AppendFieldToken(out, &wroteAny, genjsonFieldTok{{ $typeName }}{{ .GoName }})
{{- if eq .DecodeKind "string" }}
		out = strconv.AppendQuote(out, v.{{ .GoName }})
{{- else if eq .DecodeKind "ptr_string" }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else {
			out = strconv.AppendQuote(out, *v.{{ .GoName }})
		}
{{- else if eq .DecodeKind "bool" }}
		out = strconv.AppendBool(out, v.{{ .GoName }})
{{- else if eq .DecodeKind "ptr_bool" }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else {
			out = strconv.AppendBool(out, *v.{{ .GoName }})
		}
{{- else if or (eq .DecodeKind "int") (eq .DecodeKind "int8") (eq .DecodeKind "int16") (eq .DecodeKind "int32") (eq .DecodeKind "int64") (eq .DecodeKind "rune") }}
		out = strconv.AppendInt(out, int64(v.{{ .GoName }}), 10)
{{- else if or (eq .DecodeKind "ptr_int") (eq .DecodeKind "ptr_int8") (eq .DecodeKind "ptr_int16") (eq .DecodeKind "ptr_int32") (eq .DecodeKind "ptr_int64") (eq .DecodeKind "ptr_rune") }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else {
			out = strconv.AppendInt(out, int64(*v.{{ .GoName }}), 10)
		}
{{- else if or (eq .DecodeKind "uint") (eq .DecodeKind "uint8") (eq .DecodeKind "uint16") (eq .DecodeKind "uint32") (eq .DecodeKind "uint64") (eq .DecodeKind "byte") }}
		out = strconv.AppendUint(out, uint64(v.{{ .GoName }}), 10)
{{- else if or (eq .DecodeKind "ptr_uint") (eq .DecodeKind "ptr_uint8") (eq .DecodeKind "ptr_uint16") (eq .DecodeKind "ptr_uint32") (eq .DecodeKind "ptr_uint64") (eq .DecodeKind "ptr_byte") }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else {
			out = strconv.AppendUint(out, uint64(*v.{{ .GoName }}), 10)
		}
{{- else if eq .DecodeKind "float32" }}
		tmp, err := genjsonrt.AppendFloat64(out, float64(v.{{ .GoName }}), 32)
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = tmp
{{- else if eq .DecodeKind "float64" }}
		tmp, err := genjsonrt.AppendFloat64(out, v.{{ .GoName }}, 64)
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = tmp
{{- else if eq .DecodeKind "ptr_float32" }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else {
			tmp, err := genjsonrt.AppendFloat64(out, float64(*v.{{ .GoName }}), 32)
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = tmp
		}
{{- else if eq .DecodeKind "ptr_float64" }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else {
			tmp, err := genjsonrt.AppendFloat64(out, *v.{{ .GoName }}, 64)
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = tmp
		}
		{{- else if eq .DecodeKind "uuid" }}
		if tm, ok := any(v.{{ .GoName }}).(genjsonrt.TextMarshaler); ok {
			text, err := tm.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = strconv.AppendQuote(out, string(text))
		} else {
			return nil, genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
		}
		{{- else if eq .DecodeKind "ptr_uuid" }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else if tm, ok := any(*v.{{ .GoName }}).(genjsonrt.TextMarshaler); ok {
			text, err := tm.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = strconv.AppendQuote(out, string(text))
		} else {
			return nil, genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
		}
		{{- else if eq .DecodeKind "struct" }}
		b, err := Encode{{ .BaseType }}(v.{{ .GoName }})
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = append(out, b...)
		{{- else if eq .DecodeKind "slice" }}
		out = append(out, '[')
		innerAny := false
		{{- if eq .ElemKind "slice" }}
		for i := range v.{{ .GoName }} {
			out = genjsonrt.AppendCommaIfNeeded(out, &innerAny)
			out = append(out, '[')
			inner2Any := false
			for j := range v.{{ .GoName }}[i] {
				out = genjsonrt.AppendCommaIfNeeded(out, &inner2Any)
				out = strconv.AppendInt(out, int64(v.{{ .GoName }}[i][j]), 10)
			}
			out = append(out, ']')
		}
		{{- else }}
		for i := range v.{{ .GoName }} {
			out = genjsonrt.AppendCommaIfNeeded(out, &innerAny)
			{{- if eq .ElemKind "uuid" }}
			if tm, ok := any(v.{{ .GoName }}[i]).(genjsonrt.TextMarshaler); ok {
				text, err := tm.MarshalText()
				if err != nil {
					return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
				}
				out = strconv.AppendQuote(out, string(text))
			} else {
				return nil, genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
			}
			{{- else if eq .ElemKind "struct" }}
			b, err := Encode{{ .ElemType }}(v.{{ .GoName }}[i])
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = append(out, b...)
			{{- else if eq .ElemKind "string" }}
			out = strconv.AppendQuote(out, v.{{ .GoName }}[i])
			{{- else if eq .ElemKind "bool" }}
			out = strconv.AppendBool(out, v.{{ .GoName }}[i])
			{{- else }}
			// numbers
			out = strconv.AppendInt(out, int64(v.{{ .GoName }}[i]), 10)
			{{- end }}
		}
		{{- end }}
		out = append(out, ']')
		{{- else if eq .DecodeKind "map" }}
		out = append(out, '{')
		innerAny := false
		for k, vv := range v.{{ .GoName }} {
			out = genjsonrt.AppendCommaIfNeeded(out, &innerAny)
			out = strconv.AppendQuote(out, k)
			out = append(out, ':')
			{{- if eq .ElemKind "uuid" }}
			if tm, ok := any(vv).(genjsonrt.TextMarshaler); ok {
				text, err := tm.MarshalText()
				if err != nil {
					return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
				}
				out = strconv.AppendQuote(out, string(text))
			} else {
				return nil, genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
			}
			{{- else if eq .ElemKind "struct" }}
			b, err := Encode{{ .ElemType }}(vv)
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = append(out, b...)
			{{- else if eq .ElemKind "string" }}
			out = strconv.AppendQuote(out, vv)
			{{- else if eq .ElemKind "bool" }}
			out = strconv.AppendBool(out, vv)
			{{- else }}
			out = strconv.AppendUint(out, uint64(vv), 10)
			{{- end }}
		}
		out = append(out, '}')
{{- else }}
		if m, ok := any(v.{{ .GoName }}).(genjsonrt.Marshaler); ok {
			b, err := m.MarshalJSON()
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = append(out, b...)
		} else if m, ok := any(&v.{{ .GoName }}).(genjsonrt.Marshaler); ok {
			b, err := m.MarshalJSON()
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = append(out, b...)
		} else {
			return nil, genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
		}
{{- end }}
	}
{{- else }}
	out = genjsonrt.AppendFieldToken(out, &wroteAny, genjsonFieldTok{{ $typeName }}{{ .GoName }})
{{- if eq .DecodeKind "string" }}
	out = strconv.AppendQuote(out, v.{{ .GoName }})
{{- else if eq .DecodeKind "ptr_string" }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else {
		out = strconv.AppendQuote(out, *v.{{ .GoName }})
	}
{{- else if eq .DecodeKind "bool" }}
	out = strconv.AppendBool(out, v.{{ .GoName }})
{{- else if eq .DecodeKind "ptr_bool" }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else {
		out = strconv.AppendBool(out, *v.{{ .GoName }})
	}
{{- else if or (eq .DecodeKind "int") (eq .DecodeKind "int8") (eq .DecodeKind "int16") (eq .DecodeKind "int32") (eq .DecodeKind "int64") (eq .DecodeKind "rune") }}
	out = strconv.AppendInt(out, int64(v.{{ .GoName }}), 10)
{{- else if or (eq .DecodeKind "ptr_int") (eq .DecodeKind "ptr_int8") (eq .DecodeKind "ptr_int16") (eq .DecodeKind "ptr_int32") (eq .DecodeKind "ptr_int64") (eq .DecodeKind "ptr_rune") }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else {
		out = strconv.AppendInt(out, int64(*v.{{ .GoName }}), 10)
	}
{{- else if or (eq .DecodeKind "uint") (eq .DecodeKind "uint8") (eq .DecodeKind "uint16") (eq .DecodeKind "uint32") (eq .DecodeKind "uint64") (eq .DecodeKind "byte") }}
	out = strconv.AppendUint(out, uint64(v.{{ .GoName }}), 10)
{{- else if or (eq .DecodeKind "ptr_uint") (eq .DecodeKind "ptr_uint8") (eq .DecodeKind "ptr_uint16") (eq .DecodeKind "ptr_uint32") (eq .DecodeKind "ptr_uint64") (eq .DecodeKind "ptr_byte") }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else {
		out = strconv.AppendUint(out, uint64(*v.{{ .GoName }}), 10)
	}
{{- else if eq .DecodeKind "float32" }}
	tmp, err := genjsonrt.AppendFloat64(out, float64(v.{{ .GoName }}), 32)
	if err != nil {
		return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
	}
	out = tmp
{{- else if eq .DecodeKind "float64" }}
	tmp, err := genjsonrt.AppendFloat64(out, v.{{ .GoName }}, 64)
	if err != nil {
		return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
	}
	out = tmp
{{- else if eq .DecodeKind "ptr_float32" }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else {
		tmp, err := genjsonrt.AppendFloat64(out, float64(*v.{{ .GoName }}), 32)
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = tmp
	}
{{- else if eq .DecodeKind "ptr_float64" }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else {
		tmp, err := genjsonrt.AppendFloat64(out, *v.{{ .GoName }}, 64)
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = tmp
	}
	{{- else if eq .DecodeKind "uuid" }}
	if tm, ok := any(v.{{ .GoName }}).(genjsonrt.TextMarshaler); ok {
		text, err := tm.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = strconv.AppendQuote(out, string(text))
	} else {
		return nil, genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
	}
	{{- else if eq .DecodeKind "ptr_uuid" }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else if tm, ok := any(*v.{{ .GoName }}).(genjsonrt.TextMarshaler); ok {
		text, err := tm.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = strconv.AppendQuote(out, string(text))
	} else {
		return nil, genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
	}
{{- else if eq .DecodeKind "struct" }}
	b, err := Encode{{ .BaseType }}(v.{{ .GoName }})
	if err != nil {
		return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
	}
	out = append(out, b...)
{{- else if eq .DecodeKind "slice" }}
	out = append(out, '[')
	innerAny{{ .GoName }} := false
	{{- if eq .ElemKind "slice" }}
	for i := range v.{{ .GoName }} {
		out = genjsonrt.AppendCommaIfNeeded(out, &innerAny{{ .GoName }})
		out = append(out, '[')
		inner2Any := false
		for j := range v.{{ .GoName }}[i] {
			out = genjsonrt.AppendCommaIfNeeded(out, &inner2Any)
			out = strconv.AppendInt(out, int64(v.{{ .GoName }}[i][j]), 10)
		}
		out = append(out, ']')
	}
	{{- else }}
	for i := range v.{{ .GoName }} {
		out = genjsonrt.AppendCommaIfNeeded(out, &innerAny{{ .GoName }})
		{{- if eq .ElemKind "uuid" }}
		if tm, ok := any(v.{{ .GoName }}[i]).(genjsonrt.TextMarshaler); ok {
			text, err := tm.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = strconv.AppendQuote(out, string(text))
		} else {
			return nil, genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
		}
		{{- else if eq .ElemKind "struct" }}
		b, err := Encode{{ .ElemType }}(v.{{ .GoName }}[i])
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = append(out, b...)
		{{- else if eq .ElemKind "string" }}
		out = strconv.AppendQuote(out, v.{{ .GoName }}[i])
		{{- else if eq .ElemKind "bool" }}
		out = strconv.AppendBool(out, v.{{ .GoName }}[i])
		{{- else }}
		// numbers
		out = strconv.AppendInt(out, int64(v.{{ .GoName }}[i]), 10)
		{{- end }}
	}
	{{- end }}
	out = append(out, ']')
{{- else if eq .DecodeKind "map" }}
	out = append(out, '{')
	innerAny{{ .GoName }} := false
	for k, vv := range v.{{ .GoName }} {
		out = genjsonrt.AppendCommaIfNeeded(out, &innerAny{{ .GoName }})
		out = strconv.AppendQuote(out, k)
		out = append(out, ':')
		{{- if eq .ElemKind "uuid" }}
		if tm, ok := any(vv).(genjsonrt.TextMarshaler); ok {
			text, err := tm.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = strconv.AppendQuote(out, string(text))
		} else {
			return nil, genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
		}
		{{- else if eq .ElemKind "struct" }}
		b, err := Encode{{ .ElemType }}(vv)
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = append(out, b...)
		{{- else if eq .ElemKind "string" }}
		out = strconv.AppendQuote(out, vv)
		{{- else if eq .ElemKind "bool" }}
		out = strconv.AppendBool(out, vv)
		{{- else }}
		out = strconv.AppendUint(out, uint64(vv), 10)
		{{- end }}
	}
	out = append(out, '}')
{{- else }}
	if m, ok := any(v.{{ .GoName }}).(genjsonrt.Marshaler); ok {
		b, err := m.MarshalJSON()
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = append(out, b...)
	} else if m, ok := any(&v.{{ .GoName }}).(genjsonrt.Marshaler); ok {
		b, err := m.MarshalJSON()
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = append(out, b...)
	} else {
		return nil, genjsonrt.UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
	}
{{- end }}
{{- end }}
{{- end }}
	out = append(out, '}')
	return out, nil
}

{{- if $.EmitMarshaler }}
func (v {{ .Name }}) MarshalJSON() ([]byte, error) {
	return Encode{{ .Name }}(v)
}

func (v *{{ .Name }}) UnmarshalJSON(data []byte) error {
	if v == nil {
		return fmt.Errorf("nil pointer receiver for {{ .Name }}.UnmarshalJSON")
	}
	parsed, err := Decode{{ .Name }}(data)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}
{{- end }}
{{- end }}
`
