package genjson

const generatedFileTemplate = `// Code generated by genjson. DO NOT EDIT.

package {{ .PackageName }}

import (
	"encoding"
	"fmt"
	"math"
	"reflect"
	"strconv"
	{{- if .UsesUUID }}
	"github.com/google/uuid"
	{{- end }}
)

type UnknownFieldError struct {
	TypeName string
	Field    string
}

func (e UnknownFieldError) Error() string {
	return fmt.Sprintf("%s: unknown field %q", e.TypeName, e.Field)
}

type MissingFieldError struct {
	TypeName string
	Field    string
}

func (e MissingFieldError) Error() string {
	return fmt.Sprintf("%s: missing required field %q", e.TypeName, e.Field)
}

type UnsupportedFieldTypeError struct {
	TypeName string
	Field    string
	Op       string
}

func (e UnsupportedFieldTypeError) Error() string {
	return fmt.Sprintf("%s.%s: unsupported field type for %s", e.TypeName, e.Field, e.Op)
}

type genjsonMarshaler interface {
	MarshalJSON() ([]byte, error)
}

type genjsonUnmarshaler interface {
	UnmarshalJSON([]byte) error
}

type genjsonTextMarshaler interface {
	encoding.TextMarshaler
}

type genjsonTextUnmarshaler interface {
	encoding.TextUnmarshaler
}

func genjsonIsZero(v any) bool {
	if v == nil {
		return true
	}
	rv := reflect.ValueOf(v)
	return rv.IsZero()
}

type genjsonParser struct {
	data []byte
	i    int
}

func genjsonDecodeObject(data []byte, visit func(key []byte, value []byte) error) error {
	p := genjsonParser{data: data}
	p.skipWS()
	if !p.consume('{') {
		return p.errf("expected '{'")
	}

	p.skipWS()
	if p.consume('}') {
		p.skipWS()
		if p.i != len(p.data) {
			return p.errf("unexpected trailing data")
		}
		return nil
	}

	for {
		key, err := p.parseStringRaw()
		if err != nil {
			return err
		}
		p.skipWS()
		if !p.consume(':') {
			return p.errf("expected ':' after object key")
		}
		p.skipWS()

		start := p.i
		if err := p.skipValue(); err != nil {
			return err
		}

		if err := visit(key, p.data[start:p.i]); err != nil {
			return err
		}

		p.skipWS()
		if p.consume('}') {
			break
		}
		if !p.consume(',') {
			return p.errf("expected ',' or '}' in object")
		}
		p.skipWS()
	}

	p.skipWS()
	if p.i != len(p.data) {
		return p.errf("unexpected trailing data")
	}
	return nil
}

func (p *genjsonParser) skipValue() error {
	p.skipWS()
	if p.i >= len(p.data) {
		return p.errf("unexpected end of input")
	}

	switch p.data[p.i] {
	case '{':
		return p.skipObject()
	case '[':
		return p.skipArray()
	case '"':
		return p.skipStringRaw()
	case 't':
		return p.consumeLiteral("true")
	case 'f':
		return p.consumeLiteral("false")
	case 'n':
		return p.consumeLiteral("null")
	default:
		return p.skipNumber()
	}
}

func (p *genjsonParser) skipObject() error {
	if !p.consume('{') {
		return p.errf("expected '{'")
	}
	p.skipWS()
	if p.consume('}') {
		return nil
	}

	for {
		if _, err := p.parseString(); err != nil {
			return err
		}
		p.skipWS()
		if !p.consume(':') {
			return p.errf("expected ':' after object key")
		}
		if err := p.skipValue(); err != nil {
			return err
		}
		p.skipWS()
		if p.consume('}') {
			return nil
		}
		if !p.consume(',') {
			return p.errf("expected ',' or '}' in object")
		}
		p.skipWS()
	}
}

func (p *genjsonParser) skipArray() error {
	if !p.consume('[') {
		return p.errf("expected '['")
	}
	p.skipWS()
	if p.consume(']') {
		return nil
	}

	for {
		if err := p.skipValue(); err != nil {
			return err
		}
		p.skipWS()
		if p.consume(']') {
			return nil
		}
		if !p.consume(',') {
			return p.errf("expected ',' or ']' in array")
		}
		p.skipWS()
	}
}

func (p *genjsonParser) skipStringRaw() error {
	if !p.consume('"') {
		return p.errf("expected string")
	}
	for p.i < len(p.data) {
		c := p.data[p.i]
		p.i++
		if c == '\\' {
			if p.i >= len(p.data) {
				return p.errf("invalid escape sequence")
			}
			p.i++
			continue
		}
		if c == '"' {
			return nil
		}
	}
	return p.errf("unterminated string")
}

func (p *genjsonParser) parseString() (string, error) {
	raw, err := p.parseStringRaw()
	if err != nil {
		return "", err
	}
	v, err := strconv.Unquote(string(raw))
	if err != nil {
		return "", p.errf("invalid quoted string")
	}
	return v, nil
}

func (p *genjsonParser) parseStringRaw() ([]byte, error) {
	start := p.i
	if err := p.skipStringRaw(); err != nil {
		return nil, err
	}
	return p.data[start:p.i], nil
}

func genjsonKeyEq(raw []byte, want string) bool {
	// raw is a quoted JSON string slice (including quotes), want is unquoted.
	// Fast path: only supports keys without escape sequences.
	if len(raw) != len(want)+2 {
		return false
	}
	if raw[0] != '"' || raw[len(raw)-1] != '"' {
		return false
	}
	for i := 0; i < len(want); i++ {
		c := raw[i+1]
		if c == '\\' {
			return false
		}
		if c != want[i] {
			return false
		}
	}
	return true
}

func (p *genjsonParser) skipNumber() error {
	start := p.i
	if p.peek('-') {
		p.i++
	}
	if p.i >= len(p.data) {
		return p.errf("invalid number")
	}

	if p.peek('0') {
		p.i++
	} else {
		if !isDigit19(p.data[p.i]) {
			return p.errf("invalid number")
		}
		for p.i < len(p.data) && isDigit(p.data[p.i]) {
			p.i++
		}
	}

	if p.peek('.') {
		p.i++
		if p.i >= len(p.data) || !isDigit(p.data[p.i]) {
			return p.errf("invalid number")
		}
		for p.i < len(p.data) && isDigit(p.data[p.i]) {
			p.i++
		}
	}

	if p.peek('e') || p.peek('E') {
		p.i++
		if p.peek('+') || p.peek('-') {
			p.i++
		}
		if p.i >= len(p.data) || !isDigit(p.data[p.i]) {
			return p.errf("invalid number")
		}
		for p.i < len(p.data) && isDigit(p.data[p.i]) {
			p.i++
		}
	}

	if p.i == start {
		return p.errf("invalid number")
	}
	return nil
}

func (p *genjsonParser) consumeLiteral(lit string) error {
	if len(p.data)-p.i < len(lit) || string(p.data[p.i:p.i+len(lit)]) != lit {
		return p.errf("invalid literal")
	}
	p.i += len(lit)
	return nil
}

func (p *genjsonParser) skipWS() {
	for p.i < len(p.data) {
		switch p.data[p.i] {
		case ' ', '\n', '\t', '\r':
			p.i++
		default:
			return
		}
	}
}

func (p *genjsonParser) consume(ch byte) bool {
	if p.i < len(p.data) && p.data[p.i] == ch {
		p.i++
		return true
	}
	return false
}

func (p *genjsonParser) peek(ch byte) bool {
	return p.i < len(p.data) && p.data[p.i] == ch
}

func (p *genjsonParser) errf(msg string) error {
	return fmt.Errorf("json parse error at byte %d: %s", p.i, msg)
}

func isDigit(b byte) bool {
	return b >= '0' && b <= '9'
}

func isDigit19(b byte) bool {
	return b >= '1' && b <= '9'
}

func genjsonIsNull(value []byte) bool {
	return len(value) == 4 && value[0] == 'n' && value[1] == 'u' && value[2] == 'l' && value[3] == 'l'
}

func genjsonDecodeString(value []byte) (string, error) {
	if len(value) < 2 || value[0] != '"' || value[len(value)-1] != '"' {
		return "", fmt.Errorf("expected JSON string")
	}
	inner := value[1 : len(value)-1]
	// Fast path: no escapes, treat as raw UTF-8 bytes.
	for i := 0; i < len(inner); i++ {
		if inner[i] == '\\' {
			v, err := strconv.Unquote(string(value))
			if err != nil {
				return "", fmt.Errorf("invalid JSON string: %w", err)
			}
			return v, nil
		}
	}
	return string(inner), nil
}

func genjsonDecodeText(value []byte) ([]byte, error) {
	// JSON string -> bytes for TextUnmarshaler
	s, err := genjsonDecodeString(value)
	if err != nil {
		return nil, err
	}
	return []byte(s), nil
}

func genjsonDecodeArray(data []byte, visit func(elem []byte) error) error {
	p := genjsonParser{data: data}
	p.skipWS()
	if !p.consume('[') {
		return p.errf("expected '[']")
	}
	p.skipWS()
	if p.consume(']') {
		p.skipWS()
		if p.i != len(p.data) {
			return p.errf("unexpected trailing data")
		}
		return nil
	}
	for {
		p.skipWS()
		start := p.i
		if err := p.skipValue(); err != nil {
			return err
		}
		if err := visit(p.data[start:p.i]); err != nil {
			return err
		}
		p.skipWS()
		if p.consume(']') {
			break
		}
		if !p.consume(',') {
			return p.errf("expected ',' or ']' in array")
		}
	}
	p.skipWS()
	if p.i != len(p.data) {
		return p.errf("unexpected trailing data")
	}
	return nil
}

func genjsonDecodeMapObject(data []byte, visit func(key string, value []byte) error) error {
	// Similar to genjsonDecodeObject but returns decoded key strings (maps usually have arbitrary keys).
	p := genjsonParser{data: data}
	p.skipWS()
	if !p.consume('{') {
		return p.errf("expected '{'")
	}
	p.skipWS()
	if p.consume('}') {
		p.skipWS()
		if p.i != len(p.data) {
			return p.errf("unexpected trailing data")
		}
		return nil
	}
	for {
		key, err := p.parseString()
		if err != nil {
			return err
		}
		p.skipWS()
		if !p.consume(':') {
			return p.errf("expected ':' after object key")
		}
		p.skipWS()
		start := p.i
		if err := p.skipValue(); err != nil {
			return err
		}
		if err := visit(key, p.data[start:p.i]); err != nil {
			return err
		}
		p.skipWS()
		if p.consume('}') {
			break
		}
		if !p.consume(',') {
			return p.errf("expected ',' or '}' in object")
		}
		p.skipWS()
	}
	p.skipWS()
	if p.i != len(p.data) {
		return p.errf("unexpected trailing data")
	}
	return nil
}

func genjsonAppendCommaIfNeeded(dst []byte, wroteAny *bool) []byte {
	if *wroteAny {
		return append(dst, ',')
	}
	*wroteAny = true
	return dst
}

func genjsonAppendArrayStart(dst []byte, fieldWroteAny *bool) []byte {
	dst = genjsonAppendCommaIfNeeded(dst, fieldWroteAny)
	dst = append(dst, '[')
	return dst
}

func genjsonAppendArrayEnd(dst []byte) []byte { return append(dst, ']') }

func genjsonAppendObjectStart(dst []byte, fieldWroteAny *bool) []byte {
	dst = genjsonAppendCommaIfNeeded(dst, fieldWroteAny)
	dst = append(dst, '{')
	return dst
}

func genjsonAppendObjectEnd(dst []byte) []byte { return append(dst, '}') }

func genjsonDecodeBool(value []byte) (bool, error) {
	if len(value) == 4 && value[0] == 't' && value[1] == 'r' && value[2] == 'u' && value[3] == 'e' {
		return true, nil
	}
	if len(value) == 5 && value[0] == 'f' && value[1] == 'a' && value[2] == 'l' && value[3] == 's' && value[4] == 'e' {
		return false, nil
	}
	return false, fmt.Errorf("expected JSON boolean")
}

func genjsonDecodeInt(value []byte, bitSize int) (int64, error) {
	v, err := strconv.ParseInt(string(value), 10, bitSize)
	if err != nil {
		return 0, fmt.Errorf("invalid JSON integer: %w", err)
	}
	return v, nil
}

func genjsonDecodeUint(value []byte, bitSize int) (uint64, error) {
	v, err := strconv.ParseUint(string(value), 10, bitSize)
	if err != nil {
		return 0, fmt.Errorf("invalid JSON unsigned integer: %w", err)
	}
	return v, nil
}

func genjsonDecodeFloat(value []byte, bitSize int) (float64, error) {
	v, err := strconv.ParseFloat(string(value), bitSize)
	if err != nil {
		return 0, fmt.Errorf("invalid JSON float: %w", err)
	}
	return v, nil
}

func genjsonAppendFieldName(dst []byte, wroteAny *bool, name string) []byte {
	if *wroteAny {
		dst = append(dst, ',')
	} else {
		*wroteAny = true
	}
	dst = strconv.AppendQuote(dst, name)
	dst = append(dst, ':')
	return dst
}

// genjsonAppendFieldToken appends a precomputed JSON object field token of the form:
//
// 	"name":
//
// The token MUST already be quoted and MUST end with ':'.
//
// This avoids per-field strconv.AppendQuote calls in hot encode paths.
func genjsonAppendFieldToken(dst []byte, wroteAny *bool, tok []byte) []byte {
	if *wroteAny {
		dst = append(dst, ',')
	} else {
		*wroteAny = true
	}
	return append(dst, tok...)
}

func genjsonAppendFloat64(dst []byte, v float64, bitSize int) ([]byte, error) {
	if math.IsNaN(v) || math.IsInf(v, 0) {
		return nil, fmt.Errorf("unsupported float value")
	}
	return strconv.AppendFloat(dst, v, 'g', -1, bitSize), nil
}

{{- range .Types }}
{{- $type := . }}
func Decode{{ .Name }}(data []byte) ({{ .Name }}, error) {
	var out {{ .Name }}
{{- range .RequiredFields }}
	seen{{ .GoName }} := false
{{- end }}

	err := genjsonDecodeObject(data, func(key []byte, value []byte) error {
		switch {
{{- range .Fields }}
		case genjsonKeyEq(key, {{ printf "%q" .JSONName }}):
{{- if .Required }}
			seen{{ .GoName }} = true
{{- end }}
			{{- if eq .DecodeKind "string" }}
			parsed, err := genjsonDecodeString(value)
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = parsed
			{{- else if eq .DecodeKind "ptr_string" }}
			if genjsonIsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				parsed, err := genjsonDecodeString(value)
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				out.{{ .GoName }} = &parsed
			}
			{{- else if eq .DecodeKind "bool" }}
			parsed, err := genjsonDecodeBool(value)
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = parsed
			{{- else if eq .DecodeKind "ptr_bool" }}
			if genjsonIsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				parsed, err := genjsonDecodeBool(value)
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				out.{{ .GoName }} = &parsed
			}
			{{- else if or (eq .DecodeKind "int") (eq .DecodeKind "int8") (eq .DecodeKind "int16") (eq .DecodeKind "int32") (eq .DecodeKind "int64") (eq .DecodeKind "rune") }}
			parsed, err := genjsonDecodeInt(value, {{- if or (eq .DecodeKind "int") -}} 0 {{- else if or (eq .DecodeKind "int8") -}} 8 {{- else if or (eq .DecodeKind "int16") -}} 16 {{- else if or (eq .DecodeKind "int32") (eq .DecodeKind "rune") -}} 32 {{- else -}} 64 {{- end -}})
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = {{ .BaseType }}(parsed)
			{{- else if or (eq .DecodeKind "ptr_int") (eq .DecodeKind "ptr_int8") (eq .DecodeKind "ptr_int16") (eq .DecodeKind "ptr_int32") (eq .DecodeKind "ptr_int64") (eq .DecodeKind "ptr_rune") }}
			if genjsonIsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				parsed, err := genjsonDecodeInt(value, {{- if or (eq .DecodeKind "ptr_int") -}} 0 {{- else if or (eq .DecodeKind "ptr_int8") -}} 8 {{- else if or (eq .DecodeKind "ptr_int16") -}} 16 {{- else if or (eq .DecodeKind "ptr_int32") (eq .DecodeKind "ptr_rune") -}} 32 {{- else -}} 64 {{- end -}})
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				tmp := {{ .BaseType }}(parsed)
				out.{{ .GoName }} = &tmp
			}
			{{- else if or (eq .DecodeKind "uint") (eq .DecodeKind "uint8") (eq .DecodeKind "uint16") (eq .DecodeKind "uint32") (eq .DecodeKind "uint64") (eq .DecodeKind "byte") }}
			parsed, err := genjsonDecodeUint(value, {{- if eq .DecodeKind "uint" -}} 0 {{- else if or (eq .DecodeKind "uint8") (eq .DecodeKind "byte") -}} 8 {{- else if eq .DecodeKind "uint16" -}} 16 {{- else if eq .DecodeKind "uint32" -}} 32 {{- else -}} 64 {{- end -}})
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = {{ .BaseType }}(parsed)
			{{- else if or (eq .DecodeKind "ptr_uint") (eq .DecodeKind "ptr_uint8") (eq .DecodeKind "ptr_uint16") (eq .DecodeKind "ptr_uint32") (eq .DecodeKind "ptr_uint64") (eq .DecodeKind "ptr_byte") }}
			if genjsonIsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				parsed, err := genjsonDecodeUint(value, {{- if eq .DecodeKind "ptr_uint" -}} 0 {{- else if or (eq .DecodeKind "ptr_uint8") (eq .DecodeKind "ptr_byte") -}} 8 {{- else if eq .DecodeKind "ptr_uint16" -}} 16 {{- else if eq .DecodeKind "ptr_uint32" -}} 32 {{- else -}} 64 {{- end -}})
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				tmp := {{ .BaseType }}(parsed)
				out.{{ .GoName }} = &tmp
			}
			{{- else if or (eq .DecodeKind "float32") (eq .DecodeKind "float64") }}
			parsed, err := genjsonDecodeFloat(value, {{- if eq .DecodeKind "float32" -}} 32 {{- else -}} 64 {{- end -}})
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = {{ .BaseType }}(parsed)
			{{- else if or (eq .DecodeKind "ptr_float32") (eq .DecodeKind "ptr_float64") }}
			if genjsonIsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				parsed, err := genjsonDecodeFloat(value, {{- if eq .DecodeKind "ptr_float32" -}} 32 {{- else -}} 64 {{- end -}})
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				tmp := {{ .BaseType }}(parsed)
				out.{{ .GoName }} = &tmp
			}
			{{- else if eq .DecodeKind "uuid" }}
			text, err := genjsonDecodeText(value)
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			if u, ok := any(&out.{{ .GoName }}).(genjsonTextUnmarshaler); ok {
				if err := u.UnmarshalText(text); err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
			} else {
				return UnsupportedFieldTypeError{TypeName: {{ printf "%q" $type.Name }}, Field: {{ printf "%q" .GoName }}, Op: "decode"}
			}
			{{- else if eq .DecodeKind "ptr_uuid" }}
			if genjsonIsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				text, err := genjsonDecodeText(value)
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				tmp := new({{ .BaseType }})
				if u, ok := any(tmp).(genjsonTextUnmarshaler); ok {
					if err := u.UnmarshalText(text); err != nil {
						return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
					}
					out.{{ .GoName }} = tmp
				} else {
					return UnsupportedFieldTypeError{TypeName: {{ printf "%q" $type.Name }}, Field: {{ printf "%q" .GoName }}, Op: "decode"}
				}
			}
			{{- else if eq .DecodeKind "struct" }}
			parsed, err := Decode{{ .BaseType }}(value)
			if err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = parsed
			{{- else if eq .DecodeKind "ptr_struct" }}
			if genjsonIsNull(value) {
				out.{{ .GoName }} = nil
			} else {
				parsed, err := Decode{{ .BaseType }}(value)
				if err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
				tmp := parsed
				out.{{ .GoName }} = &tmp
			}
			{{- else if eq .DecodeKind "slice" }}
			{{- if eq .ElemKind "slice" }}
			var arr [][]{{ .ElemType }}
			{{- else }}
			var arr []{{ .ElemType }}
			{{- end }}
			if err := genjsonDecodeArray(value, func(elem []byte) error {
				{{- if eq .ElemKind "slice" }}
				var inner []{{ .ElemType }}
				if err := genjsonDecodeArray(elem, func(innerElem []byte) error {
					vv, err := genjsonDecodeInt(innerElem, 0)
					if err != nil {
						return err
					}
					inner = append(inner, {{ .ElemType }}(vv))
					return nil
				}); err != nil {
					return err
				}
				arr = append(arr, inner)
				return nil
				{{- end }}
				{{- if eq .ElemKind "string" }}
				v, err := genjsonDecodeString(elem)
				if err != nil { return err }
				arr = append(arr, v)
				{{- else if eq .ElemKind "bool" }}
				v, err := genjsonDecodeBool(elem)
				if err != nil { return err }
				arr = append(arr, v)
				{{- else if or (eq .ElemKind "int") (eq .ElemKind "int8") (eq .ElemKind "int16") (eq .ElemKind "int32") (eq .ElemKind "int64") (eq .ElemKind "rune") }}
				vv, err := genjsonDecodeInt(elem, 0)
				if err != nil { return err }
				arr = append(arr, {{ .ElemType }}(vv))
				{{- else if or (eq .ElemKind "uint") (eq .ElemKind "uint8") (eq .ElemKind "uint16") (eq .ElemKind "uint32") (eq .ElemKind "uint64") (eq .ElemKind "byte") }}
				vv, err := genjsonDecodeUint(elem, 0)
				if err != nil { return err }
				arr = append(arr, {{ .ElemType }}(vv))
				{{- else if or (eq .ElemKind "float32") (eq .ElemKind "float64") }}
				vv, err := genjsonDecodeFloat(elem, 64)
				if err != nil { return err }
				arr = append(arr, {{ .ElemType }}(vv))
				{{- else if eq .ElemKind "uuid" }}
				txt, err := genjsonDecodeText(elem)
				if err != nil { return err }
				var tmp {{ .ElemType }}
				if u, ok := any(&tmp).(genjsonTextUnmarshaler); ok {
					if err := u.UnmarshalText(txt); err != nil { return err }
					arr = append(arr, tmp)
					return nil
				}
				return fmt.Errorf("unsupported slice elem")
				{{- else if eq .ElemKind "struct" }}
				vv, err := Decode{{ .ElemType }}(elem)
				if err != nil { return err }
				arr = append(arr, vv)
				{{- else }}
				return fmt.Errorf("unsupported slice elem")
				{{- end }}
				return nil
			}); err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = arr
			{{- else if eq .DecodeKind "map" }}
			m := make(map[string]{{ .ElemType }})
			if err := genjsonDecodeMapObject(value, func(k string, elem []byte) error {
				{{- if eq .ElemKind "string" }}
				v, err := genjsonDecodeString(elem)
				if err != nil { return err }
				m[k] = v
				{{- else if eq .ElemKind "bool" }}
				v, err := genjsonDecodeBool(elem)
				if err != nil { return err }
				m[k] = v
				{{- else if or (eq .ElemKind "int") (eq .ElemKind "int8") (eq .ElemKind "int16") (eq .ElemKind "int32") (eq .ElemKind "int64") (eq .ElemKind "rune") }}
				vv, err := genjsonDecodeInt(elem, 0)
				if err != nil { return err }
				m[k] = {{ .ElemType }}(vv)
				{{- else if or (eq .ElemKind "uint") (eq .ElemKind "uint8") (eq .ElemKind "uint16") (eq .ElemKind "uint32") (eq .ElemKind "uint64") (eq .ElemKind "byte") }}
				vv, err := genjsonDecodeUint(elem, 0)
				if err != nil { return err }
				m[k] = {{ .ElemType }}(vv)
				{{- else if or (eq .ElemKind "float32") (eq .ElemKind "float64") }}
				vv, err := genjsonDecodeFloat(elem, 64)
				if err != nil { return err }
				m[k] = {{ .ElemType }}(vv)
				{{- else if eq .ElemKind "uuid" }}
				txt, err := genjsonDecodeText(elem)
				if err != nil { return err }
				var tmp {{ .ElemType }}
				if u, ok := any(&tmp).(genjsonTextUnmarshaler); ok {
					if err := u.UnmarshalText(txt); err != nil { return err }
					m[k] = tmp
					return nil
				}
				return fmt.Errorf("unsupported map elem")
				{{- else if eq .ElemKind "struct" }}
				vv, err := Decode{{ .ElemType }}(elem)
				if err != nil { return err }
				m[k] = vv
				{{- else }}
				return fmt.Errorf("unsupported map elem")
				{{- end }}
				return nil
			}); err != nil {
				return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
			}
			out.{{ .GoName }} = m
			{{- else }}
			if u, ok := any(&out.{{ .GoName }}).(genjsonUnmarshaler); ok {
				if err := u.UnmarshalJSON(value); err != nil {
					return fmt.Errorf("{{ $type.Name }}.{{ .GoName }}: %w", err)
				}
			} else {
				return UnsupportedFieldTypeError{TypeName: {{ printf "%q" $type.Name }}, Field: {{ printf "%q" .GoName }}, Op: "decode"}
			}
			{{- end }}
{{- end }}
{{- if $.UnknownFields }}
		default:
			// Slow path: decode key string only for error message.
			k, err := strconv.Unquote(string(key))
			if err != nil {
				k = "<invalid key>"
			}
			return UnknownFieldError{TypeName: {{ printf "%q" $type.Name }}, Field: k}
{{- end }}
		}
		return nil
	})
	if err != nil {
		return {{ .Name }}{}, err
	}

{{- if $.RequiredFieldsEnabled }}
{{- range .RequiredFields }}
	if !seen{{ .GoName }} {
		return {{ $type.Name }}{}, MissingFieldError{TypeName: {{ printf "%q" $type.Name }}, Field: {{ printf "%q" .JSONName }}}
	}
{{- end }}
{{- end }}
	return out, nil
}

func Encode{{ .Name }}(v {{ .Name }}) ([]byte, error) {
	out := make([]byte, 0, 128)
	out = append(out, '{')
	wroteAny := false
{{- $typeName := .Name }}
	{{- range .Fields }}
	// Precomputed field token: {{ .JSONName }}
	var genjsonFieldTok{{ $typeName }}{{ .GoName }} = []byte({{ printf "%q" (printf "\"%s\":" .JSONName) }})
	{{- end }}
{{- range .Fields }}
{{- if .OmitEmpty }}
	if !genjsonIsZero(v.{{ .GoName }}) {
		out = genjsonAppendFieldToken(out, &wroteAny, genjsonFieldTok{{ $typeName }}{{ .GoName }})
{{- if eq .DecodeKind "string" }}
		out = strconv.AppendQuote(out, v.{{ .GoName }})
{{- else if eq .DecodeKind "ptr_string" }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else {
			out = strconv.AppendQuote(out, *v.{{ .GoName }})
		}
{{- else if eq .DecodeKind "bool" }}
		out = strconv.AppendBool(out, v.{{ .GoName }})
{{- else if eq .DecodeKind "ptr_bool" }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else {
			out = strconv.AppendBool(out, *v.{{ .GoName }})
		}
{{- else if or (eq .DecodeKind "int") (eq .DecodeKind "int8") (eq .DecodeKind "int16") (eq .DecodeKind "int32") (eq .DecodeKind "int64") (eq .DecodeKind "rune") }}
		out = strconv.AppendInt(out, int64(v.{{ .GoName }}), 10)
{{- else if or (eq .DecodeKind "ptr_int") (eq .DecodeKind "ptr_int8") (eq .DecodeKind "ptr_int16") (eq .DecodeKind "ptr_int32") (eq .DecodeKind "ptr_int64") (eq .DecodeKind "ptr_rune") }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else {
			out = strconv.AppendInt(out, int64(*v.{{ .GoName }}), 10)
		}
{{- else if or (eq .DecodeKind "uint") (eq .DecodeKind "uint8") (eq .DecodeKind "uint16") (eq .DecodeKind "uint32") (eq .DecodeKind "uint64") (eq .DecodeKind "byte") }}
		out = strconv.AppendUint(out, uint64(v.{{ .GoName }}), 10)
{{- else if or (eq .DecodeKind "ptr_uint") (eq .DecodeKind "ptr_uint8") (eq .DecodeKind "ptr_uint16") (eq .DecodeKind "ptr_uint32") (eq .DecodeKind "ptr_uint64") (eq .DecodeKind "ptr_byte") }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else {
			out = strconv.AppendUint(out, uint64(*v.{{ .GoName }}), 10)
		}
{{- else if eq .DecodeKind "float32" }}
		tmp, err := genjsonAppendFloat64(out, float64(v.{{ .GoName }}), 32)
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = tmp
{{- else if eq .DecodeKind "float64" }}
		tmp, err := genjsonAppendFloat64(out, v.{{ .GoName }}, 64)
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = tmp
{{- else if eq .DecodeKind "ptr_float32" }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else {
			tmp, err := genjsonAppendFloat64(out, float64(*v.{{ .GoName }}), 32)
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = tmp
		}
{{- else if eq .DecodeKind "ptr_float64" }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else {
			tmp, err := genjsonAppendFloat64(out, *v.{{ .GoName }}, 64)
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = tmp
		}
		{{- else if eq .DecodeKind "uuid" }}
		if tm, ok := any(v.{{ .GoName }}).(genjsonTextMarshaler); ok {
			text, err := tm.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = strconv.AppendQuote(out, string(text))
		} else {
			return nil, UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
		}
		{{- else if eq .DecodeKind "ptr_uuid" }}
		if v.{{ .GoName }} == nil {
			out = append(out, "null"...)
		} else if tm, ok := any(*v.{{ .GoName }}).(genjsonTextMarshaler); ok {
			text, err := tm.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = strconv.AppendQuote(out, string(text))
		} else {
			return nil, UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
		}
		{{- else if eq .DecodeKind "struct" }}
		b, err := Encode{{ .BaseType }}(v.{{ .GoName }})
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = append(out, b...)
		{{- else if eq .DecodeKind "slice" }}
		out = append(out, '[')
		innerAny := false
		{{- if eq .ElemKind "slice" }}
		for i := range v.{{ .GoName }} {
			out = genjsonAppendCommaIfNeeded(out, &innerAny)
			out = append(out, '[')
			inner2Any := false
			for j := range v.{{ .GoName }}[i] {
				out = genjsonAppendCommaIfNeeded(out, &inner2Any)
				out = strconv.AppendInt(out, int64(v.{{ .GoName }}[i][j]), 10)
			}
			out = append(out, ']')
		}
		{{- else }}
		for i := range v.{{ .GoName }} {
			out = genjsonAppendCommaIfNeeded(out, &innerAny)
			{{- if eq .ElemKind "uuid" }}
			if tm, ok := any(v.{{ .GoName }}[i]).(genjsonTextMarshaler); ok {
				text, err := tm.MarshalText()
				if err != nil {
					return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
				}
				out = strconv.AppendQuote(out, string(text))
			} else {
				return nil, UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
			}
			{{- else if eq .ElemKind "struct" }}
			b, err := Encode{{ .ElemType }}(v.{{ .GoName }}[i])
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = append(out, b...)
			{{- else if eq .ElemKind "string" }}
			out = strconv.AppendQuote(out, v.{{ .GoName }}[i])
			{{- else if eq .ElemKind "bool" }}
			out = strconv.AppendBool(out, v.{{ .GoName }}[i])
			{{- else }}
			// numbers
			out = strconv.AppendInt(out, int64(v.{{ .GoName }}[i]), 10)
			{{- end }}
		}
		{{- end }}
		out = append(out, ']')
		{{- else if eq .DecodeKind "map" }}
		out = append(out, '{')
		innerAny := false
		for k, vv := range v.{{ .GoName }} {
			out = genjsonAppendCommaIfNeeded(out, &innerAny)
			out = strconv.AppendQuote(out, k)
			out = append(out, ':')
			{{- if eq .ElemKind "uuid" }}
			if tm, ok := any(vv).(genjsonTextMarshaler); ok {
				text, err := tm.MarshalText()
				if err != nil {
					return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
				}
				out = strconv.AppendQuote(out, string(text))
			} else {
				return nil, UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
			}
			{{- else if eq .ElemKind "struct" }}
			b, err := Encode{{ .ElemType }}(vv)
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = append(out, b...)
			{{- else if eq .ElemKind "string" }}
			out = strconv.AppendQuote(out, vv)
			{{- else if eq .ElemKind "bool" }}
			out = strconv.AppendBool(out, vv)
			{{- else }}
			out = strconv.AppendUint(out, uint64(vv), 10)
			{{- end }}
		}
		out = append(out, '}')
{{- else }}
		if m, ok := any(v.{{ .GoName }}).(genjsonMarshaler); ok {
			b, err := m.MarshalJSON()
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = append(out, b...)
		} else if m, ok := any(&v.{{ .GoName }}).(genjsonMarshaler); ok {
			b, err := m.MarshalJSON()
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = append(out, b...)
		} else {
			return nil, UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
		}
{{- end }}
	}
{{- else }}
	out = genjsonAppendFieldToken(out, &wroteAny, genjsonFieldTok{{ $typeName }}{{ .GoName }})
{{- if eq .DecodeKind "string" }}
	out = strconv.AppendQuote(out, v.{{ .GoName }})
{{- else if eq .DecodeKind "ptr_string" }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else {
		out = strconv.AppendQuote(out, *v.{{ .GoName }})
	}
{{- else if eq .DecodeKind "bool" }}
	out = strconv.AppendBool(out, v.{{ .GoName }})
{{- else if eq .DecodeKind "ptr_bool" }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else {
		out = strconv.AppendBool(out, *v.{{ .GoName }})
	}
{{- else if or (eq .DecodeKind "int") (eq .DecodeKind "int8") (eq .DecodeKind "int16") (eq .DecodeKind "int32") (eq .DecodeKind "int64") (eq .DecodeKind "rune") }}
	out = strconv.AppendInt(out, int64(v.{{ .GoName }}), 10)
{{- else if or (eq .DecodeKind "ptr_int") (eq .DecodeKind "ptr_int8") (eq .DecodeKind "ptr_int16") (eq .DecodeKind "ptr_int32") (eq .DecodeKind "ptr_int64") (eq .DecodeKind "ptr_rune") }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else {
		out = strconv.AppendInt(out, int64(*v.{{ .GoName }}), 10)
	}
{{- else if or (eq .DecodeKind "uint") (eq .DecodeKind "uint8") (eq .DecodeKind "uint16") (eq .DecodeKind "uint32") (eq .DecodeKind "uint64") (eq .DecodeKind "byte") }}
	out = strconv.AppendUint(out, uint64(v.{{ .GoName }}), 10)
{{- else if or (eq .DecodeKind "ptr_uint") (eq .DecodeKind "ptr_uint8") (eq .DecodeKind "ptr_uint16") (eq .DecodeKind "ptr_uint32") (eq .DecodeKind "ptr_uint64") (eq .DecodeKind "ptr_byte") }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else {
		out = strconv.AppendUint(out, uint64(*v.{{ .GoName }}), 10)
	}
{{- else if eq .DecodeKind "float32" }}
	tmp, err := genjsonAppendFloat64(out, float64(v.{{ .GoName }}), 32)
	if err != nil {
		return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
	}
	out = tmp
{{- else if eq .DecodeKind "float64" }}
	tmp, err := genjsonAppendFloat64(out, v.{{ .GoName }}, 64)
	if err != nil {
		return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
	}
	out = tmp
{{- else if eq .DecodeKind "ptr_float32" }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else {
		tmp, err := genjsonAppendFloat64(out, float64(*v.{{ .GoName }}), 32)
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = tmp
	}
{{- else if eq .DecodeKind "ptr_float64" }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else {
		tmp, err := genjsonAppendFloat64(out, *v.{{ .GoName }}, 64)
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = tmp
	}
	{{- else if eq .DecodeKind "uuid" }}
	if tm, ok := any(v.{{ .GoName }}).(genjsonTextMarshaler); ok {
		text, err := tm.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = strconv.AppendQuote(out, string(text))
	} else {
		return nil, UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
	}
	{{- else if eq .DecodeKind "ptr_uuid" }}
	if v.{{ .GoName }} == nil {
		out = append(out, "null"...)
	} else if tm, ok := any(*v.{{ .GoName }}).(genjsonTextMarshaler); ok {
		text, err := tm.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = strconv.AppendQuote(out, string(text))
	} else {
		return nil, UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
	}
{{- else if eq .DecodeKind "struct" }}
	b, err := Encode{{ .BaseType }}(v.{{ .GoName }})
	if err != nil {
		return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
	}
	out = append(out, b...)
{{- else if eq .DecodeKind "slice" }}
	out = append(out, '[')
	innerAny{{ .GoName }} := false
	{{- if eq .ElemKind "slice" }}
	for i := range v.{{ .GoName }} {
		out = genjsonAppendCommaIfNeeded(out, &innerAny{{ .GoName }})
		out = append(out, '[')
		inner2Any := false
		for j := range v.{{ .GoName }}[i] {
			out = genjsonAppendCommaIfNeeded(out, &inner2Any)
			out = strconv.AppendInt(out, int64(v.{{ .GoName }}[i][j]), 10)
		}
		out = append(out, ']')
	}
	{{- else }}
	for i := range v.{{ .GoName }} {
		out = genjsonAppendCommaIfNeeded(out, &innerAny{{ .GoName }})
		{{- if eq .ElemKind "uuid" }}
		if tm, ok := any(v.{{ .GoName }}[i]).(genjsonTextMarshaler); ok {
			text, err := tm.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = strconv.AppendQuote(out, string(text))
		} else {
			return nil, UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
		}
		{{- else if eq .ElemKind "struct" }}
		b, err := Encode{{ .ElemType }}(v.{{ .GoName }}[i])
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = append(out, b...)
		{{- else if eq .ElemKind "string" }}
		out = strconv.AppendQuote(out, v.{{ .GoName }}[i])
		{{- else if eq .ElemKind "bool" }}
		out = strconv.AppendBool(out, v.{{ .GoName }}[i])
		{{- else }}
		// numbers
		out = strconv.AppendInt(out, int64(v.{{ .GoName }}[i]), 10)
		{{- end }}
	}
	{{- end }}
	out = append(out, ']')
{{- else if eq .DecodeKind "map" }}
	out = append(out, '{')
	innerAny{{ .GoName }} := false
	for k, vv := range v.{{ .GoName }} {
		out = genjsonAppendCommaIfNeeded(out, &innerAny{{ .GoName }})
		out = strconv.AppendQuote(out, k)
		out = append(out, ':')
		{{- if eq .ElemKind "uuid" }}
		if tm, ok := any(vv).(genjsonTextMarshaler); ok {
			text, err := tm.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
			}
			out = strconv.AppendQuote(out, string(text))
		} else {
			return nil, UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
		}
		{{- else if eq .ElemKind "struct" }}
		b, err := Encode{{ .ElemType }}(vv)
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = append(out, b...)
		{{- else if eq .ElemKind "string" }}
		out = strconv.AppendQuote(out, vv)
		{{- else if eq .ElemKind "bool" }}
		out = strconv.AppendBool(out, vv)
		{{- else }}
		out = strconv.AppendUint(out, uint64(vv), 10)
		{{- end }}
	}
	out = append(out, '}')
{{- else }}
	if m, ok := any(v.{{ .GoName }}).(genjsonMarshaler); ok {
		b, err := m.MarshalJSON()
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = append(out, b...)
	} else if m, ok := any(&v.{{ .GoName }}).(genjsonMarshaler); ok {
		b, err := m.MarshalJSON()
		if err != nil {
			return nil, fmt.Errorf("{{ $typeName }}.{{ .GoName }}: %w", err)
		}
		out = append(out, b...)
	} else {
		return nil, UnsupportedFieldTypeError{TypeName: {{ printf "%q" $typeName }}, Field: {{ printf "%q" .GoName }}, Op: "encode"}
	}
{{- end }}
{{- end }}
{{- end }}
	out = append(out, '}')
	return out, nil
}

{{- if $.EmitMarshaler }}
func (v {{ .Name }}) MarshalJSON() ([]byte, error) {
	return Encode{{ .Name }}(v)
}

func (v *{{ .Name }}) UnmarshalJSON(data []byte) error {
	if v == nil {
		return fmt.Errorf("nil pointer receiver for {{ .Name }}.UnmarshalJSON")
	}
	parsed, err := Decode{{ .Name }}(data)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}
{{- end }}
{{- end }}
`
