// Code generated by genjson. DO NOT EDIT.

package basic

import (
	"fmt"
	"math"
	"reflect"
	"strconv"
)

type UnknownFieldError struct {
	TypeName string
	Field    string
}

func (e UnknownFieldError) Error() string {
	return fmt.Sprintf("%s: unknown field %q", e.TypeName, e.Field)
}

type MissingFieldError struct {
	TypeName string
	Field    string
}

func (e MissingFieldError) Error() string {
	return fmt.Sprintf("%s: missing required field %q", e.TypeName, e.Field)
}

type UnsupportedFieldTypeError struct {
	TypeName string
	Field    string
	Op       string
}

func (e UnsupportedFieldTypeError) Error() string {
	return fmt.Sprintf("%s.%s: unsupported field type for %s", e.TypeName, e.Field, e.Op)
}

type genjsonMarshaler interface {
	MarshalJSON() ([]byte, error)
}

type genjsonUnmarshaler interface {
	UnmarshalJSON([]byte) error
}

func genjsonIsZero(v any) bool {
	if v == nil {
		return true
	}
	rv := reflect.ValueOf(v)
	return rv.IsZero()
}

type genjsonParser struct {
	data []byte
	i    int
}

func genjsonDecodeObject(data []byte, visit func(key []byte, value []byte) error) error {
	p := genjsonParser{data: data}
	p.skipWS()
	if !p.consume('{') {
		return p.errf("expected '{'")
	}

	p.skipWS()
	if p.consume('}') {
		p.skipWS()
		if p.i != len(p.data) {
			return p.errf("unexpected trailing data")
		}
		return nil
	}

	for {
		key, err := p.parseStringRaw()
		if err != nil {
			return err
		}
		p.skipWS()
		if !p.consume(':') {
			return p.errf("expected ':' after object key")
		}
		p.skipWS()

		start := p.i
		if err := p.skipValue(); err != nil {
			return err
		}

		if err := visit(key, p.data[start:p.i]); err != nil {
			return err
		}

		p.skipWS()
		if p.consume('}') {
			break
		}
		if !p.consume(',') {
			return p.errf("expected ',' or '}' in object")
		}
		p.skipWS()
	}

	p.skipWS()
	if p.i != len(p.data) {
		return p.errf("unexpected trailing data")
	}
	return nil
}

func (p *genjsonParser) skipValue() error {
	p.skipWS()
	if p.i >= len(p.data) {
		return p.errf("unexpected end of input")
	}

	switch p.data[p.i] {
	case '{':
		return p.skipObject()
	case '[':
		return p.skipArray()
	case '"':
		return p.skipStringRaw()
	case 't':
		return p.consumeLiteral("true")
	case 'f':
		return p.consumeLiteral("false")
	case 'n':
		return p.consumeLiteral("null")
	default:
		return p.skipNumber()
	}
}

func (p *genjsonParser) skipObject() error {
	if !p.consume('{') {
		return p.errf("expected '{'")
	}
	p.skipWS()
	if p.consume('}') {
		return nil
	}

	for {
		if _, err := p.parseString(); err != nil {
			return err
		}
		p.skipWS()
		if !p.consume(':') {
			return p.errf("expected ':' after object key")
		}
		if err := p.skipValue(); err != nil {
			return err
		}
		p.skipWS()
		if p.consume('}') {
			return nil
		}
		if !p.consume(',') {
			return p.errf("expected ',' or '}' in object")
		}
		p.skipWS()
	}
}

func (p *genjsonParser) skipArray() error {
	if !p.consume('[') {
		return p.errf("expected '['")
	}
	p.skipWS()
	if p.consume(']') {
		return nil
	}

	for {
		if err := p.skipValue(); err != nil {
			return err
		}
		p.skipWS()
		if p.consume(']') {
			return nil
		}
		if !p.consume(',') {
			return p.errf("expected ',' or ']' in array")
		}
		p.skipWS()
	}
}

func (p *genjsonParser) skipStringRaw() error {
	if !p.consume('"') {
		return p.errf("expected string")
	}
	for p.i < len(p.data) {
		c := p.data[p.i]
		p.i++
		if c == '\\' {
			if p.i >= len(p.data) {
				return p.errf("invalid escape sequence")
			}
			p.i++
			continue
		}
		if c == '"' {
			return nil
		}
	}
	return p.errf("unterminated string")
}

func (p *genjsonParser) parseString() (string, error) {
	raw, err := p.parseStringRaw()
	if err != nil {
		return "", err
	}
	v, err := strconv.Unquote(string(raw))
	if err != nil {
		return "", p.errf("invalid quoted string")
	}
	return v, nil
}

func (p *genjsonParser) parseStringRaw() ([]byte, error) {
	start := p.i
	if err := p.skipStringRaw(); err != nil {
		return nil, err
	}
	return p.data[start:p.i], nil
}

func genjsonKeyEq(raw []byte, want string) bool {
	// raw is a quoted JSON string slice (including quotes), want is unquoted.
	// Fast path: only supports keys without escape sequences.
	if len(raw) != len(want)+2 {
		return false
	}
	if raw[0] != '"' || raw[len(raw)-1] != '"' {
		return false
	}
	for i := 0; i < len(want); i++ {
		c := raw[i+1]
		if c == '\\' {
			return false
		}
		if c != want[i] {
			return false
		}
	}
	return true
}

func (p *genjsonParser) skipNumber() error {
	start := p.i
	if p.peek('-') {
		p.i++
	}
	if p.i >= len(p.data) {
		return p.errf("invalid number")
	}

	if p.peek('0') {
		p.i++
	} else {
		if !isDigit19(p.data[p.i]) {
			return p.errf("invalid number")
		}
		for p.i < len(p.data) && isDigit(p.data[p.i]) {
			p.i++
		}
	}

	if p.peek('.') {
		p.i++
		if p.i >= len(p.data) || !isDigit(p.data[p.i]) {
			return p.errf("invalid number")
		}
		for p.i < len(p.data) && isDigit(p.data[p.i]) {
			p.i++
		}
	}

	if p.peek('e') || p.peek('E') {
		p.i++
		if p.peek('+') || p.peek('-') {
			p.i++
		}
		if p.i >= len(p.data) || !isDigit(p.data[p.i]) {
			return p.errf("invalid number")
		}
		for p.i < len(p.data) && isDigit(p.data[p.i]) {
			p.i++
		}
	}

	if p.i == start {
		return p.errf("invalid number")
	}
	return nil
}

func (p *genjsonParser) consumeLiteral(lit string) error {
	if len(p.data)-p.i < len(lit) || string(p.data[p.i:p.i+len(lit)]) != lit {
		return p.errf("invalid literal")
	}
	p.i += len(lit)
	return nil
}

func (p *genjsonParser) skipWS() {
	for p.i < len(p.data) {
		switch p.data[p.i] {
		case ' ', '\n', '\t', '\r':
			p.i++
		default:
			return
		}
	}
}

func (p *genjsonParser) consume(ch byte) bool {
	if p.i < len(p.data) && p.data[p.i] == ch {
		p.i++
		return true
	}
	return false
}

func (p *genjsonParser) peek(ch byte) bool {
	return p.i < len(p.data) && p.data[p.i] == ch
}

func (p *genjsonParser) errf(msg string) error {
	return fmt.Errorf("json parse error at byte %d: %s", p.i, msg)
}

func isDigit(b byte) bool {
	return b >= '0' && b <= '9'
}

func isDigit19(b byte) bool {
	return b >= '1' && b <= '9'
}

func genjsonIsNull(value []byte) bool {
	return len(value) == 4 && value[0] == 'n' && value[1] == 'u' && value[2] == 'l' && value[3] == 'l'
}

func genjsonDecodeString(value []byte) (string, error) {
	if len(value) < 2 || value[0] != '"' || value[len(value)-1] != '"' {
		return "", fmt.Errorf("expected JSON string")
	}
	inner := value[1 : len(value)-1]
	// Fast path: no escapes, treat as raw UTF-8 bytes.
	for i := 0; i < len(inner); i++ {
		if inner[i] == '\\' {
			v, err := strconv.Unquote(string(value))
			if err != nil {
				return "", fmt.Errorf("invalid JSON string: %w", err)
			}
			return v, nil
		}
	}
	return string(inner), nil
}

func genjsonDecodeBool(value []byte) (bool, error) {
	if len(value) == 4 && value[0] == 't' && value[1] == 'r' && value[2] == 'u' && value[3] == 'e' {
		return true, nil
	}
	if len(value) == 5 && value[0] == 'f' && value[1] == 'a' && value[2] == 'l' && value[3] == 's' && value[4] == 'e' {
		return false, nil
	}
	return false, fmt.Errorf("expected JSON boolean")
}

func genjsonDecodeInt(value []byte, bitSize int) (int64, error) {
	v, err := strconv.ParseInt(string(value), 10, bitSize)
	if err != nil {
		return 0, fmt.Errorf("invalid JSON integer: %w", err)
	}
	return v, nil
}

func genjsonDecodeUint(value []byte, bitSize int) (uint64, error) {
	v, err := strconv.ParseUint(string(value), 10, bitSize)
	if err != nil {
		return 0, fmt.Errorf("invalid JSON unsigned integer: %w", err)
	}
	return v, nil
}

func genjsonDecodeFloat(value []byte, bitSize int) (float64, error) {
	v, err := strconv.ParseFloat(string(value), bitSize)
	if err != nil {
		return 0, fmt.Errorf("invalid JSON float: %w", err)
	}
	return v, nil
}

func genjsonAppendFieldName(dst []byte, wroteAny *bool, name string) []byte {
	if *wroteAny {
		dst = append(dst, ',')
	} else {
		*wroteAny = true
	}
	dst = strconv.AppendQuote(dst, name)
	dst = append(dst, ':')
	return dst
}

func genjsonAppendFloat64(dst []byte, v float64, bitSize int) ([]byte, error) {
	if math.IsNaN(v) || math.IsInf(v, 0) {
		return nil, fmt.Errorf("unsupported float value")
	}
	return strconv.AppendFloat(dst, v, 'g', -1, bitSize), nil
}
func DecodeUser(data []byte) (User, error) {
	var out User
	seenID := false
	seenName := false
	seenEmail := false

	err := genjsonDecodeObject(data, func(key []byte, value []byte) error {
		switch {
		case genjsonKeyEq(key, "id"):
			seenID = true
			parsed, err := genjsonDecodeInt(value, 0)
			if err != nil {
				return fmt.Errorf("User.ID: %w", err)
			}
			out.ID = int(parsed)
		case genjsonKeyEq(key, "name"):
			seenName = true
			parsed, err := genjsonDecodeString(value)
			if err != nil {
				return fmt.Errorf("User.Name: %w", err)
			}
			out.Name = parsed
		case genjsonKeyEq(key, "email"):
			seenEmail = true
			parsed, err := genjsonDecodeString(value)
			if err != nil {
				return fmt.Errorf("User.Email: %w", err)
			}
			out.Email = parsed
		case genjsonKeyEq(key, "nick"):
			if u, ok := any(&out.Nick).(genjsonUnmarshaler); ok {
				if err := u.UnmarshalJSON(value); err != nil {
					return fmt.Errorf("User.Nick: %w", err)
				}
			} else {
				return UnsupportedFieldTypeError{TypeName: "User", Field: "Nick", Op: "decode"}
			}
		default:
			// Slow path: decode key string only for error message.
			k, err := strconv.Unquote(string(key))
			if err != nil {
				k = "<invalid key>"
			}
			return UnknownFieldError{TypeName: "User", Field: k}
		}
		return nil
	})
	if err != nil {
		return User{}, err
	}
	if !seenID {
		return User{}, MissingFieldError{TypeName: "User", Field: "id"}
	}
	if !seenName {
		return User{}, MissingFieldError{TypeName: "User", Field: "name"}
	}
	if !seenEmail {
		return User{}, MissingFieldError{TypeName: "User", Field: "email"}
	}
	return out, nil
}

func EncodeUser(v User) ([]byte, error) {
	out := make([]byte, 0, 128)
	out = append(out, '{')
	wroteAny := false
	out = genjsonAppendFieldName(out, &wroteAny, "id")
	out = strconv.AppendInt(out, int64(v.ID), 10)
	out = genjsonAppendFieldName(out, &wroteAny, "name")
	out = strconv.AppendQuote(out, v.Name)
	out = genjsonAppendFieldName(out, &wroteAny, "email")
	out = strconv.AppendQuote(out, v.Email)
	if !genjsonIsZero(v.Nick) {
		out = genjsonAppendFieldName(out, &wroteAny, "nick")
		if m, ok := any(v.Nick).(genjsonMarshaler); ok {
			b, err := m.MarshalJSON()
			if err != nil {
				return nil, fmt.Errorf("User.Nick: %w", err)
			}
			out = append(out, b...)
		} else if m, ok := any(&v.Nick).(genjsonMarshaler); ok {
			b, err := m.MarshalJSON()
			if err != nil {
				return nil, fmt.Errorf("User.Nick: %w", err)
			}
			out = append(out, b...)
		} else {
			return nil, UnsupportedFieldTypeError{TypeName: "User", Field: "Nick", Op: "encode"}
		}
	}
	out = append(out, '}')
	return out, nil
}
func (v User) MarshalJSON() ([]byte, error) {
	return EncodeUser(v)
}

func (v *User) UnmarshalJSON(data []byte) error {
	if v == nil {
		return fmt.Errorf("nil pointer receiver for User.UnmarshalJSON")
	}
	parsed, err := DecodeUser(data)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}
func DecodeUserPlain(data []byte) (UserPlain, error) {
	var out UserPlain
	seenID := false
	seenName := false
	seenEmail := false

	err := genjsonDecodeObject(data, func(key []byte, value []byte) error {
		switch {
		case genjsonKeyEq(key, "id"):
			seenID = true
			parsed, err := genjsonDecodeInt(value, 0)
			if err != nil {
				return fmt.Errorf("UserPlain.ID: %w", err)
			}
			out.ID = int(parsed)
		case genjsonKeyEq(key, "name"):
			seenName = true
			parsed, err := genjsonDecodeString(value)
			if err != nil {
				return fmt.Errorf("UserPlain.Name: %w", err)
			}
			out.Name = parsed
		case genjsonKeyEq(key, "email"):
			seenEmail = true
			parsed, err := genjsonDecodeString(value)
			if err != nil {
				return fmt.Errorf("UserPlain.Email: %w", err)
			}
			out.Email = parsed
		default:
			// Slow path: decode key string only for error message.
			k, err := strconv.Unquote(string(key))
			if err != nil {
				k = "<invalid key>"
			}
			return UnknownFieldError{TypeName: "UserPlain", Field: k}
		}
		return nil
	})
	if err != nil {
		return UserPlain{}, err
	}
	if !seenID {
		return UserPlain{}, MissingFieldError{TypeName: "UserPlain", Field: "id"}
	}
	if !seenName {
		return UserPlain{}, MissingFieldError{TypeName: "UserPlain", Field: "name"}
	}
	if !seenEmail {
		return UserPlain{}, MissingFieldError{TypeName: "UserPlain", Field: "email"}
	}
	return out, nil
}

func EncodeUserPlain(v UserPlain) ([]byte, error) {
	out := make([]byte, 0, 128)
	out = append(out, '{')
	wroteAny := false
	out = genjsonAppendFieldName(out, &wroteAny, "id")
	out = strconv.AppendInt(out, int64(v.ID), 10)
	out = genjsonAppendFieldName(out, &wroteAny, "name")
	out = strconv.AppendQuote(out, v.Name)
	out = genjsonAppendFieldName(out, &wroteAny, "email")
	out = strconv.AppendQuote(out, v.Email)
	out = append(out, '}')
	return out, nil
}
func (v UserPlain) MarshalJSON() ([]byte, error) {
	return EncodeUserPlain(v)
}

func (v *UserPlain) UnmarshalJSON(data []byte) error {
	if v == nil {
		return fmt.Errorf("nil pointer receiver for UserPlain.UnmarshalJSON")
	}
	parsed, err := DecodeUserPlain(data)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}
